######TO DO 
#1) set templates
#2) set variables
#3) folders needed: /tasks, /vars, /templates

#All this does is install things, no deep configurations and is more of a reference than anything

---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-17-jdk
        - docker.io
        # - postgresql postgresql-contrib

    - name: Add Jenkins key to trusted keyring
      command: curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | tee /etc/apt/trusted.gpg.d/jenkins.asc
      become: yes
      ignore_errors: yes  # Allow failure, we'll handle it

    - name: Configure Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
      become: yes

    - name: Update Jenkins/Ensure it is installed
      apt:
        name: jenkins
        update_cache: yes
        state: present
      become: yes

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
      become: yes
