---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-17-jdk
        - docker.io
        # - postgresql
        # - postgresql-contrib

    - name: Download Jenkins key
      command: curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key
      register: jenkins_key

    - name: Add Jenkins key to trusted keyring
      copy:
        content: "{{ jenkins_key.stdout }}"
        dest: "/etc/apt/trusted.gpg.d/jenkins.asc"

    - name: Configure Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
      become: yes

    - name: Update Jenkins/Ensure it is installed
      apt:
        name: jenkins
        update_cache: yes
        state: present
      become: yes

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
      become: yes
