name: Deploy React App

on:
  push:
    branches: [ "main" ]  # Triggers deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change directory to the project folder
        run: cd "comp3104 devops" && pwd  # Adjusting for spaces in directory name

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Adjust if necessary

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      # Optionally run tests if you have them configured
      - name: Run tests
        run: npm run test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
